# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno
ARDUINO_DIR = /home/tsbertalan/usr/arduino-1.8.8-linux64/arduino-1.8.8/

MONITOR_PORT = /dev/ttyUSB0
include /usr/share/arduino/Arduino.mk

#include ../../Arduino.mk
#ARDUINO_PORT = /dev/ttyUSB0
